//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public int id { get; set; }
        public string status { get; set; }
        public string restaurant_name { get; set; }
        public string request_date { get; set; }
        public string maxPreservation_time { get; set; }
        public int quantity { get; set; }
        public string pickup_date { get; set; }
        public string drop_address { get; set; }
    }
}
